version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: api
    image: straightdev:0.0.1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
    networks:
      - network

  db:
    ports:
      - "5432:5432"
    container_name: db
    image: postgres:13
    env_file:
      - .env
    networks:
      - network
networks:
  network:
