version: "3.8"

services:
  api:
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    container_name: straightdev
    image: straightdevproject/straightdev:0.0.1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
