version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: api
    image: straightdev:0.0.1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal: 172.18.0.1"

  db:
    ports:
      - "5432:5432"
    container_name: db
    image: postgres:14
    env_file:
      - .env
    networks:
      - my_network
networks:
  my_network:
